title: Bobby Showalter
email: bobby.showalter@gmail.com
description: >
  Husband. Father. Designer. Terse.

# the subpath of your site, e.g. /blog
baseurl: ""

# the base hostname & protocol for your site, e.g. http://example.com
url: "http://www.bshow.co"

twitter_username: bobbyshowalter
github_username:  orangedaisy

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
