title: Bobby Showalter
email: bobby.showalter@gmail.com
description: >
  Husband. Father. Designer.

# the subpath of your site, e.g. /blog
baseurl: ""

# the base hostname & protocol for your site, e.g. http://example.com
url: "http://www.bshow.co"

# social media profiles
codepen_username: bobbyshowalter
github_username:  orangedaisy
instagram_username: bobbyshowalter
twitter_username: bobbyshowalter

# Build settings
host: 0.0.0.0
permalink: pretty
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
